#!/usr/bin/env bash

# --------------------------------------------
# System Report Script
# --------------------------------------------

# Capture hostname
HOSTNAME=$(hostname)

# Capture the username running the script
USERNAME=$(whoami)

# Capture current date and time
DATETIME=$(date +"%Y-%m-%d %H:%M:%S")

# ------------------
# System Information
# ------------------

# Load OS release info so we can get pretty name and version
source /etc/os-release
DISTRO="$NAME $VERSION"

# Uptime, trimmed to "up X days, HH:MM"
UPTIME=$(uptime -p)

# Get CPU model name (first entry)
CPU=$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^[ \t]*//')

# Total installed RAM
RAM=$(free -h --si | awk '/^Mem:/ { print $2 }')

# Disk(s): list make/model/size for each disk
#   Use lshw to get Class=disk entries, then parse logical name, vendor, size
DISKS=$(sudo lshw -class disk 2>/dev/null \
  | awk '/logical name:/{d=$3} /vendor:/{v=$2} /size:/{s=$2} 
         /description:/{print d" - "v" - "s}' )

# Video card: use lshw display class
VIDEO=$(sudo lshw -class display 2>/dev/null \
  | awk -F: '/product:/{print $2; exit}' | sed 's/^[ \t]*//')

# Determine the interface used for the default route, then get its IP
DEFAULT_IF=$(ip route | awk '/^default/ {print $5; exit}')
HOSTADDR=$(ip -4 addr show dev "$DEFAULT_IF" \
  | awk '/inet /{print $2}' | cut -d/ -f1)

# Default gateway address
GATEWAY=$(ip route | awk '/^default/ {print $3; exit}')

# DNS server(s) from resolv.conf
DNS=$(awk '/^nameserver/ {print $2}' /etc/resolv.conf | paste -sd ", ")

# -------------
# System Status
# -------------

# Users currently logged in (unique list)
USERS=$(who | awk '{print $1}' | sort -u | paste -sd ",")

# Free space for each mounted local filesystem
DISKSPACE=$(df -h --output=target,avail -x tmpfs -x devtmpfs | sed '1d' | paste -sd "; ")

# Total number of processes running
PROCESS_COUNT=$(ps aux | wc -l)

# Load averages for the last 1, 5, and 15 minutes
LOAD_AVG=$(awk '{print $1","$2","$3}' /proc/loadavg)

# Listening TCP/UDP ports
PORTS=$(ss -tuln 2>/dev/null \
  | awk '/LISTEN/ { sub(/.*:/,"",$5); print $5 }' \
  | sort -u | paste -sd ",")

# UFW (firewall) status
UFW_STATUS=$(sudo ufw status | head -n1)

# ------------------------
# Print the system report
# ------------------------

cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS:            $DISTRO
Uptime:        $UPTIME
CPU:           $CPU
RAM:           $RAM
Disk(s):       $DISKS
Video:         $VIDEO
Host Address:  $HOSTADDR
Gateway IP:    $GATEWAY
DNS Server(s): $DNS

System Status
-------------
Users Logged In:         $USERS
Disk Space (mount:avail): $DISKSPACE
Process Count:           $PROCESS_COUNT
Load Averages (1,5,15):  $LOAD_AVG
Listening Network Ports: $PORTS
UFW Status:              $UFW_STATUS

EOF
